encoder:
  model_path: "sentence-transformers/all-MiniLM-l6-v2"

  model_kwargs: 
    device: "cuda"

  encode_kwargs:
    normalize_embeddings: False

retriever:
  passage:
    chunk_size: 10
    chunk_overlap: 2

generator:
  llm_path: "model/nous-hermes-llama-2-7b.Q4_0.gguf"
  context_length: 4096
  temperature: 0.7
  max_tokens: 20000